import { logo } from "@/lib/logo";

/* The Kanadevia Inova wordmark from the live file's own vector letters (lib/logo.ts, generated by scripts/logo.py).
   tone="color": "Kanadevia" in the brand gradient, "INOVA" in Inova blue (the live header logo).
   tone="light": all white (the live footer logo, Logo_footer.svg). tone="current": follows currentColor, so the
   header can switch it with the background. `parts` tags every letter with data-part and wraps both words in
   clip paths, so the preloader can raise the letters out of the line and wipe "INOVA" open.
   `id` keeps gradient and clip ids unique when several logos share the page. */
export function Logo({ id, tone = "color", parts = false, title = "Kanadevia Inova", className = "" }: {
  id: string; tone?: "color" | "light" | "current"; parts?: boolean; title?: string; className?: string;
}) {
  const [, , w, h] = logo.viewBox;
  const grad = `${id}-grad`;
  const top = tone === "color" ? `url(#${grad})` : tone === "light" ? "#fff" : "currentColor";
  const bottom = tone === "color" ? logo.blue : tone === "light" ? "#fff" : "currentColor";
  return <svg className={`logo logo-${tone} ${className}`} viewBox={`0 0 ${w} ${h}`} role={title ? "img" : undefined} aria-label={title || undefined} aria-hidden={title ? undefined : true} focusable="false">
    <defs>
      {tone === "color" && <linearGradient id={grad} gradientUnits="userSpaceOnUse" x1={logo.gradient.x1} y1="0" x2={logo.gradient.x2} y2="0">
        {logo.gradient.stops.map((s) => <stop key={s.offset} offset={s.offset} stopColor={s.color} />)}
      </linearGradient>}
      {parts && <>
        {/* "Kanadevia" line: letters rise from below its baseline (y 44.4) and stay hidden until they cross it. */}
        <clipPath id={`${id}-top`}><rect x="-4" y="-24" width={w + 8} height="70" /></clipPath>
        {/* "INOVA": a rect that grows left to right (the wipe). */}
        <clipPath id={`${id}-wipe`}><rect data-part="wipe" x="0" y="52" width={w} height="46" /></clipPath>
      </>}
    </defs>
    <g fill={top} clipPath={parts ? `url(#${id}-top)` : undefined}>
      {logo.kanadevia.map((p) => <path key={p.id} d={p.d} data-part={parts ? p.id : undefined} data-letter={parts ? "" : undefined} />)}
    </g>
    <g fill={bottom} clipPath={parts ? `url(#${id}-wipe)` : undefined} data-part={parts ? "inova" : undefined}>
      {logo.inova.map((p) => <path key={p.id} d={p.d} />)}
    </g>
  </svg>;
}
