"""Split the live Kanadevia Inova wordmark into letters for the logo component and the preloader.

Source: https://ionacapital.co.uk/wp-content/uploads/2021/02/kanadevia.svg (the header logo, viewBox 0 0 286.3 96.38).
  - "Kanadevia" is ONE clip path of 15 sub-paths, painted with an embedded 620x128 PNG gradient.
  - "INOVA" is five paths filled #2862a0.
The gradient PNG is sampled into an SVG linearGradient so nothing raster is kept, and the sub-paths are grouped into
letters (a counter is merged into the letter whose outline contains it). Writes:
  lib/logo.ts                     letters + gradient stops for components/Logo.tsx and components/Preloader.tsx
  public/brand/kanadevia-inova-{dark,light}.svg   transparent full lock-ups (colour on light / white on dark)
  public/brand/kanadevia-inova-{kanadevia,inova}.svg  the two words on their own
  app/icon.svg                    favicon: the gradient "K" on a white tile

Run: python3 scripts/logo.py  (needs fontTools + Pillow; reads _scrape/kanadevia.svg, re-downloads it if missing)
"""

import base64
import io
import json
import os
import re
import urllib.request

from fontTools.pens.boundsPen import BoundsPen
from fontTools.svgLib.path import parse_path
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "_scrape", "kanadevia.svg")
URL = "https://ionacapital.co.uk/wp-content/uploads/2021/02/kanadevia.svg"
VIEW_W, VIEW_H = 286.3, 96.38
INOVA_BLUE = "#2862a0"  # the live file's .cls-2 fill

if not os.path.exists(SRC):
    os.makedirs(os.path.dirname(SRC), exist_ok=True)
    urllib.request.urlretrieve(URL, SRC)
svg = open(SRC).read()


def bounds(d):
    pen = BoundsPen(None)
    parse_path(d, pen)
    return pen.bounds  # xMin, yMin, xMax, yMax


def subpaths(d):
    return ["M" + p for p in d.split("M") if p.strip()]


def inside(inner, outer):
    return inner[0] >= outer[0] and inner[1] >= outer[1] and inner[2] <= outer[2] and inner[3] <= outer[3]


def letters(parts):
    """Group sub-paths into letters: outlines first, counters merged into the outline that contains them."""
    boxes = [(p, bounds(p)) for p in parts]
    outers = [(p, b) for p, b in boxes if not any(o is not b and inside(b, o) for _, o in boxes)]
    grouped = []
    for p, b in sorted(outers, key=lambda pb: pb[1][0]):
        holes = [q for q, c in boxes if c is not b and inside(c, b)]
        grouped.append({"d": "".join([p] + holes), "box": [round(v, 2) for v in b]})
    return grouped


# --- "Kanadevia": the clip path, letter by letter. The i's stem and its dot stay separate parts.
clip = re.search(r'<clipPath id="clippath"><path[^>]*d="([^"]+)"', svg).group(1)
top = letters(subpaths(clip))
names = ["K", "a1", "n", "a2", "d", "e", "v", "i", "dot", "a3"]
by_x = sorted(top, key=lambda g: (g["box"][0], g["box"][1]))
# the dot (y 0.6 to 11) and the stem (y 15.9 to 44.4) share an x range: order the stem before the dot
i_parts = [g for g in by_x if 240 < g["box"][0] < 244]
i_parts.sort(key=lambda g: -g["box"][1])
by_x = [g for g in by_x if g not in i_parts]
idx = next(n for n, g in enumerate(by_x) if g["box"][0] > 244)
by_x[idx:idx] = i_parts
assert len(by_x) == len(names), f"expected {len(names)} parts, got {len(by_x)}"
kanadevia = [{"id": n, **g} for n, g in zip(names, by_x)]

# --- "INOVA": five filled paths (O and A carry their counters already)
inova_paths = re.findall(r'<path class="cls-2" d="([^"]+)"', svg)
inova = sorted(({"d": d, "box": [round(v, 2) for v in bounds(d)]} for d in inova_paths), key=lambda g: g["box"][0])
inova = [{"id": n, **g} for n, g in zip(["I", "N", "O", "V", "A"], inova)]

# --- the gradient: the embedded PNG (placed at translate(-5.21 -7.94) scale(.48)) sampled along the word's centre line
png = re.search(r"base64,([^\"]+)", svg).group(1)
img = Image.open(io.BytesIO(base64.b64decode(png))).convert("RGB")
x0, x1 = kanadevia[0]["box"][0], kanadevia[-1]["box"][2]
stops = []
for t in [0, 0.25, 0.5, 0.75, 1]:
    vx = x0 + (x1 - x0) * t
    px = min(img.width - 1, max(0, round((vx + 5.21) / 0.48)))
    r, g, b = img.getpixel((px, img.height // 2))
    stops.append({"offset": t, "color": f"#{r:02x}{g:02x}{b:02x}"})
grad = {"x1": round(x0, 2), "x2": round(x1, 2), "stops": stops}

# --- outputs
data = {"viewBox": [0, 0, VIEW_W, VIEW_H], "blue": INOVA_BLUE, "gradient": grad, "kanadevia": kanadevia, "inova": inova}
with open(os.path.join(ROOT, "lib", "logo.ts"), "w") as f:
    f.write("// Generated by scripts/logo.py from the live wordmark (ionacapital.co.uk/wp-content/uploads/2021/02/kanadevia.svg). Do not edit.\n")
    f.write("export type LogoPart = { id: string; d: string; box: number[] };\n")
    f.write("export const logo = " + json.dumps(data, indent=1) + " as const;\n")


def grad_def(gid):
    s = "".join(f'<stop offset="{st["offset"]}" stop-color="{st["color"]}"/>' for st in stops)
    return f'<linearGradient id="{gid}" gradientUnits="userSpaceOnUse" x1="{grad["x1"]}" y1="0" x2="{grad["x2"]}" y2="0">{s}</linearGradient>'


def write(name, body, view=f"0 0 {VIEW_W} {VIEW_H}"):
    with open(os.path.join(ROOT, "public", "brand", name), "w") as f:
        f.write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view}">{body}</svg>\n')


top_d = "".join(p["d"] for p in kanadevia)
bottom_d = "".join(p["d"] for p in inova)
os.makedirs(os.path.join(ROOT, "public", "brand"), exist_ok=True)
write("kanadevia-inova-dark.svg", f'<defs>{grad_def("g")}</defs><path fill="url(#g)" d="{top_d}"/><path fill="{INOVA_BLUE}" d="{bottom_d}"/>')
write("kanadevia-inova-light.svg", f'<path fill="#fff" d="{top_d}{bottom_d}"/>')
write("kanadevia-inova-kanadevia.svg", f'<defs>{grad_def("g")}</defs><path fill="url(#g)" d="{top_d}"/>', "0 0 286.3 46")
write("kanadevia-inova-inova.svg", f'<path fill="{INOVA_BLUE}" d="{bottom_d}"/>', "0 54 175 42")

k = kanadevia[0]["box"]
pad = 6
side = max(k[2] - k[0], k[3] - k[1]) + pad * 2
cx, cy = (k[0] + k[2]) / 2, (k[1] + k[3]) / 2
view = f"{cx - side / 2:.2f} {cy - side / 2:.2f} {side:.2f} {side:.2f}"
icon = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view}"><defs>{grad_def("g")}</defs>'
        f'<rect x="{cx - side / 2:.2f}" y="{cy - side / 2:.2f}" width="{side:.2f}" height="{side:.2f}" rx="{side * 0.18:.2f}" fill="#fff"/>'
        f'<path fill="url(#g)" d="{kanadevia[0]["d"]}"/></svg>\n')
open(os.path.join(ROOT, "app", "icon.svg"), "w").write(icon)
print("letters:", [p["id"] for p in kanadevia], [p["id"] for p in inova])
print("gradient:", [s["color"] for s in stops])
